# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/hirsute64"
  config.vm.network "public_network", use_dhcp_assigned_default_route: true
  config.vm.provision "shell", inline: <<-SHELL
    echo -n                                          >  /etc/profile.d/gopath.sh
    echo 'export GOROOT=/usr/local/go'                 >> /etc/profile.d/gopath.sh
    echo 'export GOPATH=/home/vagrant/go'             >> /etc/profile.d/gopath.sh
    echo 'export PATH=$PATH:$GOROOT/bin:$GOPATH/bin' >> /etc/profile.d/gopath.sh
  SHELL
  config.vm.provision "shell", path: "golang-install.sh"
  #config.vm.provision "file", source: "../web-server.go", destination: "web-server.go"
end
